### ISSUE TITLE
If MQTT mode set to all, Brightness goes to 100

### ISSUE THREAD

**Issue by spants** [partofthething/infopanel#16]
If I change modes, it will pick up the brightness associated with the mode. However, if I use 'all' the brightness defaults to 100% and I cant change it.

Maybe pick up the brightness for each of the modes or the default when using 'all'?

**Comment by partofthething** [comment]
Ah yes, good report. Thanks! That's a defect in the `init_modes` function of [driver.py](https://github.com/partofthething/infopanel/blob/master/infopanel/driver.py) where it just applies one brightness to all scenes in that mode. 

Some complications (which can be worked around):
* User input of brightnesses is currently on the `mode` level (mode being a collection of scenes/durations/brightnesses tuples). Maybe we can alternatively allow a scene-level default brightness to be configured that the `all` mode would use, but which `modes` could still override. 
* User control of the brightness via the network should still probably override everything

**Comment by partofthething** [comment]
Fixed.
