### ISSUE TITLE
Mode Setting

### ISSUE THREAD

**Issue by SJoWie80** [partofthething/infopanel#18]
mosquitto_pub -h 192.168.101.102 -m "blank" -t house/screen/mode
or
mosquitto_pub -h 192.168.101.102 -m "all" -t house/screen/mode

result in:
INFO:infopanel.driver:Applying mode: b'blank'
ERROR:infopanel.driver:Invalid mode: b'blank'
INFO:infopanel.driver:Applying mode: b'all'
ERROR:infopanel.driver:Invalid mode: b'all'

**Comment by partofthething** [comment]
Thanks for the report. I can fix that.

**Comment by partofthething** [comment]
Should be fixed with 93d4517affac. Can you try it out and see if fixed?

**Comment by partofthething** [comment]
:thumbsup:
