### ISSUE TITLE
config.py - change parameters to support faster raspberries

### ISSUE THREAD

**Issue by spants** [partofthething/infopanel#19]
The line in config.py should be amended to support faster Pis                       
old: 
'led-slowdown-gpio': vol.All(int, vol.Range(min=0, max=2))

new:                         
'led-slowdown-gpio': vol.All(int, vol.Range(min=0, max=4))

sorry I don't know how to do a pull request!

**Comment by partofthething** [comment]
Thanks! On it.

**Comment by partofthething** [comment]
fixed in 52e7a0741d0de
