### ISSUE TITLE
Incompatible with most recent version of Voluptuous

### ISSUE THREAD

**Issue by jonhanford** [partofthething/infopanel#4]
After installing and configuring and trying to fire up the thing, I was encountering this error: 

`voluptuous.error.MultipleInvalid: expected a list for dictionary value @ data['frames']`

Having just installed this yesterday, the setup script installed voluptuous-0.11.1

I took a look at requirements.txt and saw it specifies GREATER than 0.9.3, so I figured i'd give a shot to rolling that back to the specified version. That cleared the error, and once I troubleshot more basic issues with my YAML, I was at least getting a "hello world" displayed on the panel triggered by mqtt. Haven't waded much past that just yet. 

_if anyone else is reading this with that problem, before the code is patched, here's what you do_
`sudo pip uninstall voluptuous`
`sudo pip install voluptuous==0.9.3`

Anyway - easily fixed on the user end - seems to otherwise work great, thank you for sharing. 
Mostly raising the issue in case anyone else has it, to share the fix.

**Comment by partofthething** [comment]
Fixed in de05c26b748251ae90403105e406374777992b0d. Thanks a million!

**Comment by partofthething** [comment]
The actual error is fixed in e858e0eab8635c8 so it runs on modern voluptuous again now.
